# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PantomimeMailOSX' do
  pod 'OpenSSL', '~> 1.0'
end

target 'PantomimeMailOSXTests' do
  pod 'OpenSSL', '~> 1.0'
end

target 'PantomimeMailOSXUITests' do
  pod 'OpenSSL', '~> 1.0'
end

